DAG animation
alijdens/spark-board pull request #18
Opened 2023-06-09 04:05 UTC by alijdens

Animate the nodes in react-flow DAGs as if they were connected to their `targetPosition` with a spring. The animation will stop once the nodes have reached their target position the forces are small enough.

[Screencast from 09-06-23 01:11:32.webm](https://github.com/alijdens/spark-board/assets/63980668/bc3dc510-f833-483d-9136-aeff2c80787a)

* Also, the viewport is now fit to the DAG size in the final layout in the begining.
* Minimap now shows DAG colors
* Added a toolbar button to reset the DAG to the original position (as shown in the video).
![image](https://github.com/alijdens/spark-board/assets/63980668/ea00d8c2-bb22-4e9a-8c7b-969663852401)
* Added a pannel to enable or disable settings. The default setting values can be defined from `spark-board`.
![image](https://github.com/alijdens/spark-board/assets/63980668/f1d98efd-4f33-442d-bef4-9c81ad16d6b7)

2023-06-09 18:21 UTC, eze210 requested changes

2023-06-11 00:27 UTC, alijdens commented on spark-board-ui/src/App.jsx
> +    const [nodePositions, setNodePositions] = React.useState(new Map(
done

2023-06-11 00:27 UTC, alijdens commented on spark-board-ui/src/useDagAnimation/createSystem.js
> +    for(let [id, i] of nodeIdMapping) {
fixed

2023-06-11 00:27 UTC, alijdens commented on spark_board/html.py
> -        "position": positions[node],
done

2023-06-11 01:33 UTC, eze210 approved these changes

2023-06-11 14:54 UTC, merged